### ISSUE TITLE
User Custom Fields via PHP Code

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#169]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Show how to use `get_user_option('s2_[custom_field]')`
- [x] Show how to use `get_user_option('[custom field]')`
- [x] Show how to use `get_user_field['[custom_field]')`

---

**Markdown File:** http://wsharks.com/1H81qfo
**Published KB Article:** http://s2member.com/kb-article/user-custom-fields-via-php-code/

---

**Comment by jaswsinc** [comment]
Referencing: http://s2member.com/kb-article/s2get-shortcode-documentation/

**Comment by Sonja3** [comment]
"How can we improve this article?"

Show the return value when it fails e.g. ` false`

**Comment by raamdev** [comment]
@Sonja3 Thank you for the feedback. I've updated the KB article to improve the documentation.

**Comment by DougJoseph** [comment]
If this is not the right place for this question, please let me know.

I'm thankful for the method provided, but I also need to access custom s2member fields in getting an email sent to the admin whenever a member edits a custom field in their profile.

There is some info in WP Codex about comparing old values to new values here:
https://codex.wordpress.org/Plugin_API/Action_Reference/profile_update

...and I'm using code from an article here:
http://revelationconcept.com/wordpress-send-admin-notification-user-updates-profile/

Below is an example of a couple of "actions" needed for custom fields. 
`// IF HOME PHONE NUMBER CHANGES
function sr_user_profile_update_home_ph( $user_id, $old_user_data ) {
 
  $old_user_data = get_transient( 'sr_old_user_data_' . $user_id );
  $user = get_userdata( $user_id );
 
  if($old_user_data->phone != $user->phone) {
    $admin_email = "admin@wvupci.org";
    $message = sprintf( __( 'This minister has updated their profile on the WV/wMD Ministers site.' ) ) . "\r\n\r\n";
    $message .= sprintf( __( 'Minister Name: %s' ), $user->display_name ). "\r\n\r\n";
    $message .= sprintf( __( 'Old Phone: %s' ), $old_user_data->home-ph ). "\r\n\r\n";
    $message .= sprintf( __( 'New Phone: %s' ), $user->home-ph ). "\r\n\r\n";
    wp_mail( $admin_email, sprintf( __( '[WV/wMD Ministers Site] User Profile Update' ), get_option('blogname') ), $message );
  }
 
}
 
add_action( 'profile_update', 'sr_user_profile_update_home_ph', 10, 2 );
 
// IF CELL PHONE NUMBER CHANGES
function sr_user_profile_update_cell_ph( $user_id, $old_user_data ) {
 
  $old_user_data = get_transient( 'sr_old_user_data_' . $user_id );
  $user = get_userdata( $user_id );
 
  if($old_user_data->phone != $user->phone) {
    $admin_email = "admin@wvupci.org";
    $message = sprintf( __( 'This minister has updated their profile on the WV/wMD Ministers site.' ) ) . "\r\n\r\n";
    $message .= sprintf( __( 'Minister Name: %s' ), $user->display_name ). "\r\n\r\n";
    $message .= sprintf( __( 'Old Phone: %s' ), $old_user_data->cell-ph ). "\r\n\r\n";
    $message .= sprintf( __( 'New Phone: %s' ), $user->cell-ph ). "\r\n\r\n";
    wp_mail( $admin_email, sprintf( __( '[WV/wMD Ministers Site] User Profile Update' ), get_option('blogname') ), $message );
  }
 
}
 
add_action( 'profile_update', 'sr_user_profile_update_cell_ph', 10, 2 );`

These actions use the shorter name of the fields, for example:
`home-ph`
...instead of:
`ws-plugin--s2member-profile-home-ph`
 
Do you have any advice for me on getting access to the custom fields in a comparison of old value versus newly updated value?

Thanks in advance for any and all help or advice...

-Doug

**Comment by DougJoseph** [comment]
Re: my question above, I'm now looking at the following line:

`$old_user_data = get_transient( 'sr_old_user_data_' . $user_id );`

I'm studying how the old info for the member is obtained.

The following is present further down, in the cost sample I'm trying to work with:

 `// Save old user data and meta for later comparison for non-standard fields (phone, address etc.)
function sr_old_user_data_transient(){
 
  $user_id = get_current_user_id();
  $user_data = get_userdata( $user_id );
  $user_meta = get_user_meta( $user_id );
 
  foreach( $user_meta as $key=>$val ){
    $user_data->data->$key = current($val);
  }
 
  // 1 hour should be sufficient
  set_transient( 'sr_old_user_data_' . $user_id, $user_data->data, 60 * 60 );
 
}
add_action('show_user_profile', 'sr_old_user_data_transient');
 
// Cleanup when done
function sr_old_user_data_cleanup( $user_id, $old_user_data ){
  delete_transient( 'sr_old_user_data_' . $user_id );
}
add_action( 'profile_update', 'sr_old_user_data_cleanup', 1000, 2 );
`
