### ISSUE TITLE
Do s2Member Pro-Forms work with PayPal Standard; i.e., without PayPal Pro?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#171]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/171-do-s2member-pro-forms-work-with-paypal-standard-i-e-without-paypal-pro.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/171-do-s2member-pro-forms-work-with-paypal-standard-i-e-without-paypal-pro.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/do-s2member-pro-forms-work-with-paypal-standard-i-e-without-paypal-pro/

---

**Comment by yaronelh** [comment]
Hi Jason 

This article was a great help for me, since I can't obtain a pro account in my region, at least for now.
a great addition would be to say a few words on the behavior of Pro-forms when used with a standard PayPal account (The method in the article). Something like.

"Although this method is not ideal, all the pro-form functionalities such as billing updates, billing modifications, Cancellations etc. will still work as expected when using this method."

Just a suggestion you're welcome to rephrase,
will save the guesswork

Cheers
Yaron

**Comment by Grandesigns** [comment]
This documentation is no longer accurate. s2Member (Pro) no longer allows the generation of Pro-Forms with PayPal Standard.
