### ISSUE TITLE
[s2Member-Profile /] Shortcode

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#195]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/features/2015/195-s2member-profile-shortcode.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/features/2015/195-s2member-profile-shortcode.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/s2member-profile-shortcode/

---

**Comment by jaswsinc** [comment]
Woohoo! Fantastic article.
_A tear of joy falls down my face._

**Comment by yaronelh** [comment]
If you're already talking about the profile a good idea would be to add, how to display to the user the current version he is listed to, time to the end of the subscription, how to upgrade the subscription

The kind of information you would expect on your profile page (which is also the settings in this case) 

I'm currently struggling to add this exact information so it would have been really helpful to have it in an article that's about the user profile

Cheers

**Comment by raamdev** [comment]
@yaronelh Thank you for the suggestions. There's already a KB Articles that explain those:

- [How do I display the EOT Date/Time?](http://s2member.com/kb-article/how-do-i-display-the-eot-on-my-login-welcome-page/)
- [\[s2Get /\] Shortcode Documentation](http://s2member.com/kb-article/s2get-shortcode-documentation/)
- [Customizing your Login Welcome Page](http://s2member.com/kb-article/customizing-your-login-welcome-page/)

If you want to show the current Membership Level, you can use `[s2Get constant="S2MEMBER_CURRENT_USER_ACCESS_LABEL" /]` (see **s2Member → API / Scripting → s2Member PHP/API Constants**).

I will update this KB article to include links to those KB Articles at the bottom. :-)

**Comment by yaronelh** [comment]
Thanks for including those but It was just an example, there are still things missing their and in those articles, like a last charge, date of charge, history of transaction, amount of previous charges and so-and-so

the [s2Get /] Article answers this partly but even there some fields are missing and the numbers returned from the get requests are strange, per se if you request a date you get some long number instead of an actual date. 

What I'm saying is not all of them are ready to use just by placing the code

Hope you get my point,

**Comment by raamdev** [comment]
@yaronelh The "the numbers returned" is a Unix Timestamp and [How do I display the EOT Date/Time?](http://s2member.com/kb-article/how-do-i-display-the-eot-on-my-login-welcome-page/) article explains how to resolve that. If you have a feature request, please submit a new GitHub Issue on the [s2Member GitHub Repo](https://github.com/websharks/s2member/issues/). If you need support or help with understanding how something in s2Member works, please post your question on the [Community Forum](http://wordpress.org/support/plugin/s2member) or [open a support ticket](http://s2member.com/support/) if you are Pro customer.

**Comment by yaronelh** [comment]
I didn't come here to search for support, I already opened a support ticket regarding those issues and I think it's been 4 days haven't received anything yet.

If the article was to include the information there wouldn't be a need to even contact support, the fact that you answered in this manner suggest that you don't really want to know about problems in the articles, believe me I read through a lot of the articles (plus the 3 you have mentioned) and problems are abundant, what I reported was a fraction of what I encountered in the last 3 days

I was under the impression that feedback was a desired thing, good thing I didn't have the time to send the actual amount of issues encountered :)

BTW - I am a pro customer that's why I have an interest in making the product better.

I'll save you the reports on future issues
Cheers,

**Comment by raamdev** [comment]
@yaronelh We love feedback and if you took what I said to indicate we don't want your feedback then you misunderstood. I was simply stating that if you have a support question, please ask the question in the correct channel. 

You said that you submitted a support ticket and its been 4 days without hearing back. Can you tell me what is your ticket number?

**Comment by yaronelh** [comment]
it is #6596

But what I'm basically asking is where are all the things a user might expect to see on his profile page, It is also under the assumption that I might be missing something/looking at the wrong page

Anyway.... don't worry about it I won't send you all the things I find, simply because I don't have the time :) Just the key stuff.

In general you have an awesome product, a bit lacking on the UX which makes the learning curve high but overall It's cool

**Comment by yaronelh** [comment]
Sorry about the 4 days thing, I was wrong It wasn't that long

**Comment by raamdev** [comment]
@yaronelh We do have a full KB Article that provides various tips for customizing the Login Welcome Page (i.e., the My Profile, or My Account page). Please see:

- [Customizing your Login Welcome Page](http://s2member.com/kb-article/customizing-your-login-welcome-page/)

If you have suggestions for what other examples we can add to that KB Article, I suggest leaving that feedback in [the GitHub Issue for that article](https://github.com/websharks/s2member-kb/issues/124).

**Comment by yaronelh** [comment]
Thanks, will do
