### ISSUE TITLE
How do I manually uninstall s2Member?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#227]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How do I manually uninstall s2Member?](http://s2member.com/kb-article/how-do-i-manually-uninstall-s2member/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/227-how-do-i-manually-uninstall-s2member.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/227-how-do-i-manually-uninstall-s2member.md)

---

**Comment by patdumond** [comment]
### Complete Uninstall or File Replacement?

You've decided you need to uninstall s2Member for some reason. Now you want to know the best way to do that. The first question: Do I need to retain my s2Member data? If the answer is "No" and you never plan to look back, uninstalling is pretty straight-forward. 

#### Completely Uninstall s2Member Files and Data

If you've decided you are never going to use s2Member again, you should completely remove all files and data associated with the plugin. Keep in mind that if you follow this path and change your mind about using s2Member, you will have to reinstall and reconfigure everything. So be sure this is what you want to do, especially if you've been using s2Member for some time and have it deeply woven into your website.

- [ ] Backup your files and database. (You can **never** say you will never look back!)
- [ ] Disable s2Member *Plugin Deletion Safeguards*: **Word Press Dashboard → s2Member → General Options → Plugin Deletion Safeguards**. Set to "No (upon deletion, erase all data/options)".
- [ ] Navigate to **WordPress Dashboard → Plugins**.
- [ ] Deactivate the *s2Member Framework* plugin.
- [ ] Delete the *s2Member Framework* plugin. Select "Yes, Delete these files and data" when prompted.
- [ ] Using your preferred method of file access on your webserver, delete the `/wp-content/plugins/s2member-pro/`directory. This should be the only s2Member directory remaining if you followed the instructions above. If it is not, remove all directories starting with "s2member".

#### Remove the Plugin in Order to Reinstall

If you're having some problems with s2Member and need to remove and reinstall the plugin, follow this checklist:

- [ ] Backup your files and database. 
- [ ] Enable s2Member *Plugin Deletion Safeguards*: **Word Press Dashboard → s2Member → General Options → Plugin Deletion Safeguards**. Set to "Yes (safeguard  all data/options)".
- [ ] Navigate to **WordPress Dashboard → Plugins**.
- [ ] Deactivate the *s2Member Framework* plugin.
- [ ] Delete the *s2Member Framework* plugin. Select "Yes, Delete these files and data" when prompted.
- [ ] Using your preferred method of file access, delete the following directories on your webserver:
	- [ ] `s2member`
	- [ ] `s2member-pro`
	- [ ] `s2member-extras`
- [ ] Make another backup of your files and database. 

Now you can reinstall *s2Member* and *s2Member (Pro). (Don't forget to make another backup when you're finished! :) )

**Comment by jaswsinc** [comment]
Nice work! I'll suggest a couple of edits here.

- "**Word Press**" should be "**WordPress**". Looks like an auto-correct might have mangled this in a couple places is all.

- The `s2member-extras` folder should not exist on any WordPress installation, so I think we could remove this from the article. This folder is part of the pro repo at GitHub, but I don't remember this ever being generated on the site itself.

- In this article, we should probably go through and detail what each of the `s2member-*` folders contain, and offer some tips before you delete all of them.

  ## `s2member-*` Folder Tips

  - `/wp-content/plugins/s2member-files` is generated automatically by s2Member. It is usually OK to just delete this folder and its contents as part of the uninstall. In fact, s2Member will do this for you automatically with Plugin Deletion Safeguards disabled.

    However, the purpose of this directory is for it to contain protected file downloads that you offer members. If s2Member sees that you've placed any files in this directory, it will be left as-is for your review; i.e., you will need to remove it manually. If you find that to be the case, it's worth a quick review of what this directory contains before you delete it. In other words, make sure you're not deleting downloadable files that you intend to keep as part of your offering to users.

  - `/wp-content/plugins/s2member-logs` This folder is generated automatically by s2Member. It is usually OK to just delete this folder and its contents as part of the uninstall. In fact, s2Member will do this for you automatically with Plugin Deletions Safeguards disabled. However, if you find that it still exists for some reason, it might be worth a quick review before you delete it. Just check to see if there are any archived log files in this directory that you care about, and back those up before you wipe them away.

  - `/wp-content/plugins/s2member-pro` This folder contains all of the s2Member Pro add-on files; e.g., additional payment gateway integrations and code that powers pro-only features in s2Member. It is safe to remove this folder (and its contents) as part of the uninstall process.

 - `/wp-content/plugins/s2member` This folder contains the s2Member Framework; i.e., it is the s2Member plugin itself. It is safe to remove this folder (and its contents) as part of the uninstall process. In fact, WordPress should remove this automatically whenever you deactivate and delete the plugin from your WordPress Dashboard.

---

As a point of reference, here is the uninstall routine in s2Member.
https://github.com/websharks/s2member/blob/000000-dev/s2member/includes/classes/installation.inc.php#L174

**Comment by jaswsinc** [comment]
I would also remove the `- [ ]` checkboxes from the Markdown in this article. Those checkboxes are a part of GitHub-flavored Markdown and may not work properly on the live site at s2member.com. What you can do is just omit the `[]` and make it a list item; i.e., `- ` instead of `- [] `.

**Comment by raamdev** [comment]
> What you can do is just omit the [ ] and make it a list item; i.e., - instead of - [ ].

Even better, if the list items are intended to be steps in a process (e.g., step 1, step 2, etc.), then using the ordered list item format would make more sense:

**Ordered List:**

```
1. Item
1. Item
1. Item
1. Item
```

Results in:

1. Item
1. Item
1. Item
1. Item

**Unordered List:**

```
- Item
- Item
- Item
- Item
```

Results in:

- Item
- Item
- Item
- Item

--- 

This article has use for both types: The uninstallation steps should be using the ordered list format (`1. Item`), and then list of folder types should be using the unordered list format (`- Item`)

**Comment by patdumond** [comment]
Great idea, Raam. Done.

**Comment by jaswsinc** [comment]
Additional data that you might add to the beginning of this article.

---

Uninstalling s2Member is easy. It uninstalls like any other plugin in WordPress. Just "deactivate" s2Member and then "delete" the plugin from your WordPress Dashboard. If you're running s2Member Pro, log in via FTP and delete the `s2member-pro` add-on directory also.

_Having said that, s2Member is a larger/complex plugin that packs a lot of functionality. Therefore, whenever you uninstall it there are a few things that you might want to consider._

## Plugin Deletion Safeguards

Whenever you deactivate and delete s2Member, if you want s2Member to _completely_ erase all of its options, WordPress Roles, log files, etc.; please be sure to disable Plugin Deletion Safeguards first.

See: **Dashboard → s2Member → General Options → Plugin Deletion Safeguards**

#### QUESTION: If I turn Plugin Deletion Safeguards off, will s2Member also delete members? i.e., my users? What data is being guarded when this is on?

No. s2Member will never delete users. Here is a list of the things that s2Member deletes whenever Plugin Deletion Safeguards have been turned off before an uninstall occurs.

- s2Member-generated Roles in WordPress; e.g., s2Member Level1, s2Member Level 2, etc. Note that the "Subscriber" Role is also used by s2Member, but that Role is actually a part of the WordPress core, so it is left intact.

- s2Member plugin configuration options; e.g., payment gateway credentials, restriction options, coupon codes, tax configuration data, custom registration/profile fields generated with s2Member, etc.

- s2Member-related CRON jobs are terminated; e.g., the Auto-EOT system.

- s2Member-related plugin directories; e.g., `s2member-files`, `s2member-logs`, etc.

- s2Member-related transient values that are stored in the WordPress database; e.g., IPN processing history, simultaneous login monitoring data, and other temporary/transient data that s2Member uses.

- s2Member-related metadata; i.e., data that is attached to user accounts, or to specific posts/pages in WordPress. For instance, the Paid Subscr. ID for each customer, the payment gateway they used, the CCAPs they have, their EOT time, etc. In the case of posts/pages, s2Member will drop restriction options, CCAP requirements, and things like `s2member_force_ssl`. These bits of information are only used by s2Member, and therefore it is all deleted when s2Member is removed.

**Comment by raamdev** [comment]
> Additional data that you might add to the beginning of this article.

Great suggestions, @jaswsinc! :-) 

@patdumond Would you mind editing Jason's suggestions into your draft?

**Comment by jaswsinc** [comment]
One other suggestion is to start each main heading with `##` instead of `###`; i.e., H2 instead of H3.

**My thoughts on this:** The KB article title is an H1 tag once it is published on the site, so I don't use `#` headings in the article body. However, for the sake of consistency I have been using `##` and working down from there in any headings that I create.

@raamdev Thoughts on this?

**Comment by patdumond** [comment]
Added Jason's comments.

**Comment by jaswsinc** [comment]
@raamdev I went ahead and drafted this article and moved it into a MD file. I'm going to reference this KB article in the Dashboard under Plugin Deletion Safeguards, so I wanted to get it onto the site and have a URL that I could reference. However, I will leave it unpublished for the moment and await your final review. http://s2member.com/kb-article/how-do-i-manually-uninstall-s2member/

_Therefore, this article needs to be reviewed/published before our next release._

**Comment by jaswsinc** [comment]
![2015-07-18_21-22-54](https://cloud.githubusercontent.com/assets/1563559/8764647/3300799c-2d93-11e5-8b96-4337f2ffa8d4.png)

**Comment by jaswsinc** [comment]
@raamdev Looks fantastic!
