### ISSUE TITLE
Introduction to TLS/SSL and Why You Need It on Your s2Member Site

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#232]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Introduction to TLS/SSL and Why You Need It on Your s2Member Site](http://s2member.com/kb-article/introduction-to-tlsssl-and-why-you-need-it-on-your-s2member-site/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/232-introduction-to-tlsssl-and-why-you-need-it-on-your-s2member-site.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/232-introduction-to-tlsssl-and-why-you-need-it-on-your-s2member-site.md)

---

**Comment by jaswsinc** [comment]
TSL should be TLS

**Comment by patdumond** [comment]
Yes, yes it should. :)

**Comment by patdumond** [comment]
Please take a look and provide feedback on this draft. I need help with tagging suggestions and ideas for a closing (besides "tell them what you told them"). Thanks in advance.

**Comment by raamdev** [comment]
Tag suggestions: `security, s2member-security-badge`

---

I suggest changing the title to the following:

- **Introduction to TLS/SSL and Why You Need It on Your s2Member Site**

---

The screenshot of `https://` in the browser is a bit small and doesn't really stand out. The red bookmarks bar in the screenshot is actually the thing that draws my attention (not the green `https://` in the address bar), so you might try hiding the bookmarks bar in the screenshot and maybe even adding an arrow to point out the `https://`.

---

Regarding an ending to the article: Since you're planning to write a follow-up that explains how to implement SSL on your s2Member site, I suggest creating another H2 (`##`) called something like **How Do I Implement SSL?** that briefly summarizes this article and the benefits of using SSL and then introduces in a small way the follow-up article, with a link to it.

**Comment by jaswsinc** [comment]
Nice work! I'll leave my comments while Raam is reviewing.

- This screenshot contains your bookmarks bar, and it might be easier for a reader to focus on the address bar if it was not in this screenshot. 

  ![](https://cloud.githubusercontent.com/assets/9320495/8882433/cd7790d4-3214-11e5-8c19-7c84bb0c4857.png)

_Maybe it would help if you took one that contains the top of the browser with standard browser controls, but then crop out the personal bookmarks bar._

**Comment by raamdev** [comment]
Also, "WikiPedia" should be "Wikipedia". :-)

**Comment by patdumond** [comment]
I think this is ready for a final review and publication if nobody has any other edits to make.

**Comment by raamdev** [comment]
@patdumond Looks great now! Thanks! :-) 

I replaced your screenshot for the `https://` with one that does not include the EV (Extended Validation) certificate. The EV Certificate is a lot more expensive and allows you to have the Company Name in the address bar like your GitHub screenshot, however most people will not pay the $600+/year for that certificate and will instead have a standard certificate that shows up like this:

![A site secured with HTTPS](https://cloud.githubusercontent.com/assets/53005/9013196/7f8c5bd8-3788-11e5-8719-beaa22e071e9.png)

Having a screenshot of the EV certificate might make people wonder why theirs doesn't look like that. :-)
