### ISSUE TITLE
How can I let a customer set the amount they will pay?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#233]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How can I let a customer set the amount they will pay?](http://s2member.com/kb-article/how-can-i-let-a-customer-set-the-amount-they-will-pay/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/233-how-can-i-let-a-customer-set-the-amount-they-will-pay.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/233-how-can-i-let-a-customer-set-the-amount-they-will-pay.md)

---

**Comment by RealDavidoff** [comment]
I hope you see this, it took me two hours to prepare...:

I happily found above article on websharks Jason, but I am afraid to say I can't get it work the way described. So I finally ended up trying first JUST the generated shortcode alone (Capability Buy Now Stripe Pro Form, for donations), and even that behaves so different to what I understand it's supposed to behave. Let me show you what I mean, the screenshots will help, but they come as attachments because I can't see how to display them here directly (and some items renamed/hidden for privacy, rest 100% genuine shortcode generator outputs):

1) Firstly, the "donator" is asked to log in (see screenshot 1), while I understood from your article *and* from the s2m docu that the donator need NOT log in (which is very sensible).

2) The "donator" is asked to "Create a Profile" (see screenshot 1), which a) again he shouldn't need to, and b) this doesn't make sense when he's asked to log in anyway (which itself doesn't make sense, see above).

3) The form further displays all the additional Registration fields. So then I reviewed this part of the docu: "Regarding Registration: Custom Fields do not appear during repeat registration and/or checkout attempts (i.e., they do not appear for any user that is currently logged into the site). Please make sure that you test registration and/or checkout forms while not logged in (i.e., please test as a first-time customer). Existing users, members, customers may update Custom Fields by editing their Profile." 
This makes it even less clear (and is contradictory IMO): a) what is a "repeat registration"?, can the visitor register repeatedly? b) We clearly have generated the shortcode for a "checkout attempt", yet the custom fields DO appear. c) if custom fields "do not appear for any user that is currently logged into the site" then how can "Existing users, members, customers may update Custom Fields by editing their Profile"? 
In my experience they CAN, because custom fields DO appear "for any user that is currently logged into the site", namely when they edit their profile. I feel, the entire paragraph need to be rewritten so that I (and other customers?) can understand it.

4) Then the form shows "Add Billing Method .... Powered by Stripe" (screenshot 2). And only AFTER the donator clicks on that, the stripe checkout form pops up. But the whole purpose of the widget code (that transfers the chosen amount) is to display straight away the final donation/payment form, not to make the customer jump through MORE loops, click ever MORE buttons before he may donate (if he's still there at this point...?). So, suggestion (because this part I gladly do understand): Instead of all that undesirable registration stuff, display the stripe "billing method" (their checkout form!) directly. Remember, the lovely visitor is already on the second page now, he had to wait for it to load, etc. Hopefully he is still with us!?

5) Then the form enforces yet another headline onto the user (read scroll down): "Checkout Now" (he still wasn't allowed to make his donation), and there it shows "Tick - Yes, I know I may receive updates via email!" - What updates? He wants to donate. I noticed that on EVERY form I generate, s2m adds that (Mailchimp) subscription message at the end. How can we avoid that? It makes only sense on the ONE form that serves the purpose to subscribe. I have tried different settings for many months (since I bought s2m) but can't get rid of that, sorry if I sound incompetent.

6) Now on to the form that gets displayed WHEN I use that redirection described in the article (screenshot 4). The "?"s mean: I don't understand. None of that. :-(

7) I also tried other shortcode generator buttons, eg that the donator first registers for free. Again I was unsuccessful to get what I'd expect to see. So then I reviewed more docu: Level: "...Free Registration Forms will accept any value [0-4] (or, up to the number of configured Levels). With Independent Custom Capabilities this MUST be set to level="*", and ccaps="" must NOT be empty (i.e., level="*" ccaps="music,videos")." 
- MUST be set to level="*" does not work, output says Form Error Undefined level. So I changed level back to 1, only then it works.

To shorten this now (need to go to bed): I just can't get a simple stripe donation with "Pro Forms" to work! I got so frustrated that I thought "I better ask stripe if THEY have a widget for us". But everytime I look at your insanely great(!) plugin (you remember how much I promote it, THAT awesome it is!) I am thinking: "there must be a way, after all Jason has coded and docu'ed all this". Please can you show me (and others) how?

(If Github is not the right place (was linked on your site) just redirect me)
screenshot 1
![jason1](https://cloud.githubusercontent.com/assets/11789004/12862994/7a1dcf86-cc68-11e5-9ec2-e64c8a980e90.png)
screenshot 2
![jason2](https://cloud.githubusercontent.com/assets/11789004/12862995/7a264cb0-cc68-11e5-9053-74fa4960e16f.png)
screenshot 3
![jason3](https://cloud.githubusercontent.com/assets/11789004/12862996/7a2ca83a-cc68-11e5-8647-56aa4f302fa0.png)
screenshot 4
![jason4](https://cloud.githubusercontent.com/assets/11789004/12862997/7a5e6852-cc68-11e5-9832-f09db8e497fc.png)

**Comment by raamdev** [comment]
@RealDavidoff 

- [How can I process credit cards directly on my page with Stripe, instead of using the popup?](http://s2member.com/kb-article/how-can-i-process-credit-cards-directly-on-my-page-with-stripe-instead-of-using-the-popup/)
- [Can I customize Pro-Forms?](http://s2member.com/kb-article/can-i-customize-pro-forms/)
- [How can I let a customer set the amount they will pay? i.e., can I accept donations?](http://s2member.com/kb-article/how-can-i-let-a-customer-set-the-amount-they-will-pay/)
- s2Member is not designed primarily for donation-based websites; it's designed for membership-based websites. You can certainly customize it to make it work the way you want, but that will take some programming experience and some understanding of how s2Member and WordPress internals work.
- If you don't want users to have to login or to be asked to login, use Specific Post/Page Buy Now forms; all other forms are designed for membership-type access where users are expected to login.

**Comment by RealDavidoff** [comment]
@raamdev 
For Specific Post/Page Buy Now forms we have to "Select a Leading Post/Page that you've protected". So do you mean the stripe payment "button" code should go on a PROTECTED page, just in case someone "inelegible" to donate would try to donate/ to pay, in s2m language?

And if so, why isn't that mentioned in this article (link again: https://s2member.com/kb-article/how-can-i-let-a-customer-set-the-amount-they-will-pay/)? 

My understanding of the article is that the code is NOT for a Specific Post/Page. We would like to follow that article's concept, it sounds so plausible/sensible. And yes, s2m certainly is for memberships, I know, but have you counted all appearances of free/unregistered/donations? Jason clearly wants to offer this feature, based on all of those (and it makes so much sense in this kind of software: s.o. who donates today may be a member tomorrow; an existin member may want to give a little extra, etc...).

**Comment by raamdev** [comment]
@RealDavidoff If you need support, please [open a support ticket](http://s2member.com/support/). We reserve this space for discussing specific improvements to specific KB Articles. This is not the space for getting support.

**Comment by RealDavidoff** [comment]
I am sorry, have you even READ what the customer wrote? The customer is *dissecting* the article that linked to this very page for feedback on the article, and he shows - even with screenshots(!) - where the article does not match the described outcome (and on a sidenote the customer is even commending the greatness of the plugin overall!), and all you can reply to the DETAILED improvement suggestions to the article (and if you decide, to the plugin) is this?

Sure I will raise a "support" ticket although this is NOT about support but about clarification or improvement of the article to reach the same results with the plugin shown off in the article. However Raam, many who read this will appreciate *answers as precise as the points raised* (not necessarily with screenshots though) - but *they* won't bother to raise a "ticket" (or buy the product!) if THIS is your reply. VERY FEW take the time, you know that.

I was glad that you quickly became a new participant of this thread because initially I addressed Jason as he was the only participant here. If this is what upsets you, just say so. But make sure you value two-hours-worth of customer feedback as much as I do.

**Comment by RealDavidoff** [comment]
Again: How can we improve this article? 

Added: And then when the user clicks the "submit form" button (screenshot 3 above, now also tested with specific page/post as suggested by Raam) then s2m uses tinyurl, although bitly api key is saved in s2m since purchase day. I trust this feedback is helpful too.

I know you say customers can customize the forms (hey they can do a lot more than than, if they have the skill) but wouldn't it help everyone if the provided *standard form* can be used as described in the article that links here? I think so. And very few if any users will know why they should "submit the form" after they've just submitted the form and paid above in the stripe pop-up.

Anyway, our test users clicked again "submit form", and then s2m shows at the top 2.00 USD Thank you!! although the user just (test) paid $16 via stripe - because the variable amount transfer described in the article, that works. When the form was generated, we put in $2 (article says "Set the amounts to anything you like, we will alter them later with the ezPHP plugin"), thus it seems that "Jason's" form still thinks the user paid $2 (bad wording, I am not a programmer) while the stripe payment form knows the amount has been changed to $16 on the fly.

This too is confusing: User thinks "did I pay $2 or did I pay $16?" - Without hacking the files (remember, no programmer on this end), how can we get the amounts displayed consistent?

(This is my final question and suggestion re/ the article, cause we reached the end of testing :-)

**Comment by raamdev** [comment]
> I am sorry, have you even READ what the customer wrote? The customer is dissecting the article that linked to this very page for feedback on the article

@RealDavidoff Yes, I have read what you wrote, several times, which was necessary because there was so much to read, so much that was related to so many different areas of the plugin (NOT specific to what this article covers) which required that I constantly change mental contexts to figure out what parts of what you wrote were a feature request, what parts might have been a bug report, and what parts were just general feedback on the article itself (which is what this space is intended for). 

I greatly appreciate your feedback and your detailed analysis, so please don't take this the wrong way. This is simply not the right space for such a long-winded, detailed analysis. We LOVE getting feedback like this, as it helps us better understand how our software is being used.

I would like you invite you to [Slack](http://slack.com), which is what we use for our team chat and collaboration. We have a hangout channel there where feedback like this can be read by everyone on our team and then we can take your feedback and open GitHub issues and/or update KB articles where necessary. If you send me your email address (you can mail it to raam at websharks-inc dot com if you want it to remain private), I'll send you an invite to our Slack team. :-)
