### ISSUE TITLE
Basic Import/Export Guide

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#244]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---
## Published @ s2Member.com: http://s2member.com/kb-article/basic-usermember-importexport-guide/

[Edit Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/244-basic-user-member-import-export-guide.md)

**Comment by jaswsinc** [comment]
> First go to Wordpress Dashboard -> s2Member -> Import/Export -> s2Member Options

Please use this symbol for Dashboard paths: `→`

**Comment by jaswsinc** [comment]
@renzms Do you have a copy of SnagIt for Windows? Or another screenshot tool?
https://www.techsmith.com/snagit.html

I suggest some screenshots for this article.

**Comment by patdumond** [comment]
@renzms Good article. Suggestion: Since this is a "newbie-friendly" explanation of Import/Export, you might want to tell them what a *CSV* file is. I see you linked it, but that takes them away from your article. Just `CSV (a Comma-Separated Values file is a text file which can be read by any text editor, spreadsheet, or database program). 

I also think you should include links to the "more advanced" KB articles about the Import/Export tools:

* [Advanced Import/Export Tools](http://s2member.com/kb-article/advanced-importexport-tools/)
* [Importing/Updating Users](http://s2member.com/kb-article/importingupdating-users/)
* [How do I open the Import/Export CSV using OpenOffice?](http://s2member.com/kb-article/how-do-i-open-the-importexport-csv-using-openoffice/)
* [How do I save the Import/Export CSV with Excel on Mac OS X?](http://s2member.com/kb-article/how-do-i-save-the-importexport-csv-with-excel-on-mac-os-x/)
* [How do I force a specific EOT with the Advanced Import/Export Tools?](http://s2member.com/kb-article/how-do-i-force-a-specific-eot-with-the-advanced-importexport-tools/)

**Comment by renzms** [comment]
> Do you have a copy of SnagIt for Windows? Or another screenshot tool?
> https://www.techsmith.com/snagit.html
> 
> I suggest some screenshots for this article.

@jaswsinc  Thanks Jason, I use QSnap for Chrome, but I'll check that out too.



> I see you linked it, but that takes them away from your article. Just CSV (a Comma-Separated Values file is a text file which can be read by any text editor, spreadsheet, or database program) would work.
> 
> I also think you should include links to the "more advanced" KB articles about the Import/Export tools:

@patdumond Hi Pat, Thanks for the corrections and suggestions! I'll add those changes in, I agree they improve the article from a "newbie's" standpoint.
