### ISSUE TITLE
Why Am I Getting a "Missing First Name" Error?

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#255]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Why Am I Getting a "Missing First Name" Error?](http://s2member.com/kb-article/why-am-i-getting-a-missing-first-name-error/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2016/255-why-am-i-getting-a-missing-first-name-error.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2016/255-why-am-i-getting-a-missing-first-name-error.md)

---

**Comment by patdumond** [comment]
_From @jaswsinc on August 12, 2015 0:46_

@patdumond I think you put this into the wrong repo by mistake.
It should go in: https://github.com/websharks/s2member-kb/issues

**Comment by patdumond** [comment]
@jaswsinc - Is there a way I can move it without deleting & creating a new issue. (I don't want you to DO it, I just want to know whether **I** can do it (and how)). :) Thanks in advance.

**Comment by patdumond** [comment]
_From @jaswsinc on August 12, 2015 13:23_

There's nothing in GitHub itself that allows for an issue to be moved (that I'm aware of), but you can just copy it from here, paste it over there, and then close this one. Good enough :-)

See also: https://github-issue-mover.appspot.com/
~ I haven't used this myself, but Raam suggested it a while back.

**Comment by patdumond** [comment]
The app worked like a charm. :)

**Comment by jaswsinc** [comment]
Cool.

**Comment by patdumond** [comment]
@raamdev: I think I have it in the right place now.

**Comment by raamdev** [comment]
@patdumond Thank you. I've reviewed the draft and provided some feedback below: :smile: 

---------

> Why Am I Getting a "Missing First Name" Error on My Custom Template Registration Form?

- [ ] I'd change this title to just "Why Am I Getting a "Missing First Name" Error?"

> Reference Zendesk Ticket #7276 
> Reference Zendesk Ticket #7753

- [ ] We don't want to reference tickets in our KB Articles.

> When using a custom template for a Pro-Form, you need to be sure that you are "using the right tool for the job".

- [ ] The intro here doesn't really tell me what this article is about. A summary that explains the issue and the solution in a few sentences would be good.

> `paymentgateway-registration-form.php`

- [ ] I suggest using the format `[payment-gateway]-registration-form.php`

> Paid Registration Form Template(s)

- [ ] The screenshot here is unnecessary.

> Oops! I Used a Paid Registration Shortcode with a Free Registration Template

- [ ] I would move this section to the top, underneath the introduction, and rename it to "Error: Missing First Name." I also suggest changing this section from first-person to second-person and explaining a bit more here that _this is what happens when you use the wrong template+shortcode combination_.

> The shortcode:

- [ ] This says 'shortcode' but what follows is a screenshot of a form with an error message... that's confusing to me.

> Screenshots (various)

- [ ] The screenshots in this KBA are of different sizes and makes them visually unappealing. Also, the middle screenshot ("form produced by this shortcode") seems to have some visual artifact or corruption.

> The Infamous Missing First Name Error Message

- [ ] This section could be merged into the "Error: Missing First Name." section.

> Recap: Use the Right Tool for the Job

- [ ] "Recap: Template Type Must Match Shortcode Type"

> Custom registration form for level 1 members paying by PayPal.

- [ ] This doesn't need to be in code style; double-quotes or italics seem more appropriate here.

**Comment by patdumond** [comment]
@raamdev: I believe I've addressed all your requested revisions.

**Comment by raamdev** [comment]
@patdumond Thank you. Looks great! **Approved as of 2016-04-04.**
