### ISSUE TITLE
Does s2Member store any billing information?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#256]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Does s2Member store any billing information?](http://s2member.com/kb-article/does-s2member-store-any-billing-information/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/256-does-s2member-store-any-billing-information.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/256-does-s2member-store-any-billing-information.md)

---

**Comment by raamdev** [comment]
@jaswsinc Can can you confirm/deny that s2Member does not collect any billing information even in the log files? I seem to recall _some_ information related to billing being logged when logging is enabled, but I don't believe that applies to things like billing addresses and credit card numbers; is that correct?

Is there any other information that you think would be useful in this KB article?

**Comment by jaswsinc** [comment]
> Can can you confirm/deny that s2Member does not collect any billing information

s2Member log files do contain personally identifiable information and even credit card numbers, expiration dates, and CVV codes. We do our best to XXXX those out, but the purpose of log files is to gather information for the purpose of debugging the software or your own implementation.

We highly recommend that logging be disabled once your site goes live, and that you contact the NSA and have them permanently delete, destroy, and burn all drives that contained those log files in order to avoid the Hillary effect--which can come back to haunt you later.

> Is there any other information that you think would be useful in this KB article?

Maybe some screenshots of Log Viewer in s2Member.

**Comment by GhostMech** [comment]
Damn, this is really funny. But on a serious note, it's why I went with 
Stripe; no data to breach for me to get sued.

**Comment by patdumond** [comment]
@jaswsinc wrote: We highly recommend that logging be disabled once your site goes live, and that you contact the NSA and have them permanently delete, destroy, and burn all drives that contained those log files in order to avoid the Hillary effect--which can come back to haunt you later.

A log chipper works. ;)

**Comment by jaswsinc** [comment]
> A log chipper works. ;)

:smile: Good idea!
