### ISSUE TITLE
Controlling Nav Menu Visibility

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#257]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Controlling Nav Menu Visibility](http://s2member.com/kb-article/controlling-nav-menu-visibility/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2015/257-controlling-nav-menu-visibility.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2015/257-controlling-nav-menu-visibility.md)

---

**Comment by patdumond** [comment]
@renzms: Make sure you include a note or something in this KB about the opposite: How to Show Menus with Protected Content to Everyone. I see this question all the time and really should have done a KB by now. ;)

**Comment by jaswsinc** [comment]
@renzms Great idea for an article and this looks great!

Couple of suggestions:

- Use `**bold**` dashboard paths instead of backticks. At s2Member.com we have a filter that converts bold Dashboard paths into blue highlighted paths with a WordPress dashboard icon in front. In order for that to work you need `**bold**` dashboard paths.

  ```
  **Dashboard → s2Member® → Restriction Options → Alternative View Protection**
  ```

- Change `is_user_logged_in` to `is_user_logged_in()` to help indicate that it's a function that you are referencing. It's obvious to me already, but that's a part of being consistent in the way that we write articles and documentation. The same for `wp_nav_menu()`.

- In your PHP code sample, specify the language syntax for syntax highlighting. This works here at GitHub and it also works once the article is published at s2Member.com.

		```php
		<?php
		$hello = 'world';
		```

  See: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by jaswsinc** [comment]
See also: https://wordpress.org/plugins/menu-items-visibility-control/screenshots/
~ This is another great way to protect navigation menu items.

**Comment by jaswsinc** [comment]
@renzms I like the latest changes. Thanks :-)

**Comment by raamdev** [comment]
@renzms Looking good! :-) Here's some feedback:

- [ ] Write an introduction to this tutorial at the top. Include a paragraph or two that explains what problem you're solving, and summarizes the solution(s).
- [ ] Create a new H2 header called something like "Using s2Member's Alternative View Protection" that separates the introduction from the part where you explain Alternative View Protection
- [ ] Include a screenshot of s2Member’s Alternative View Protection right beneath the menu path 
- [ ] Create a new H2 header called something like "Tweaking your Theme Files" that separates the Alternative View Protection section from the part where you explain how to edit theme files
- [ ] Change the title of this article to, "Controlling Nav Menu Visibility"
- [ ] Add an H2 at the bottom called, "Removing Nav Menu Visibility Restrictions" that explains what Pat mentioned above: How to Show Menus with Protected Content to Everyone. Simply explain in this section that if you want everyone to see all menu items, you can simply uncheck the Nav Menus option in Alternative View Protection so that s2Member does not hide any menu items.

_Please don't check off the items in the list above--leave them for me to check off once I've reviewed your changes. Or, if you want to check them off as you're working on them, just be sure to uncheck them all when you'e ready for me to review your changes._

---

Also, I noticed Jason requested some changes above but I don't see any comments from you here indicating that you applied those changes. I see that you did apply them, but I had to go and look through the article to see if you did. Please leave a comment here on this GitHub issue (and not just in Slack, since there's no way to see your Slack comment when I'm looking at this GitHub issue).

**Comment by renzms** [comment]
@raamdev 

>Please don't check off the items in the list above--leave them for me to check off once I've reviewed your changes. Or, if you want to check them off as you're working on them, just be sure to uncheck them all when you'e ready for me to review your changes.

Ok, cool thanks. I will probably check them off on a separate task list widget I have.

>Also, I noticed Jason requested some changes above but I don't see any comments from you here indicating that you applied those changes. I see that you did apply them, but I had to go and look through the article to see if you did. Please leave a comment here on this GitHub issue (and not just in Slack, since there's no way to see your Slack comment when I'm looking at this GitHub issue).

Noted, I'll stick to this GitHub issue when I need to make comments or if I have questions about it here.

**Comment by renzms** [comment]
@raamdev I've made changes according to your checklist, along with some changes I thought would help the article flow better.

It's ready for another check and any comments/corrections you may have.

**Comment by raamdev** [comment]
@renzms Awesome work! It really looks great now. There are a few more small edits I request before marking this approved:

- [ ] In your screenshot, please turn off shadows on the lines and arrows. The shadows make it harder to read the text inside the red box and are unnecessary for the arrows.
- [ ] This article is short enough that the anchored text in the introduction is not necessary; please remove those anchor links from the introduction.
- [ ] "Here is a sample for two separate Navigation Menus" ← 'a sample' should be 'an example'. 
- [ ] "theme’s header.php file directly," ← 'header.php' should be in code style, i.e., `header.php`.
- [ ] "(`/wp-admin/nav-menus.php`)" ← Remove this; there's no need to point to that file for this example.
- [ ] "using the following:" ← Replace that with, "using [`is_user_logged_in()`](http://codex.wordpress.org/Function_Reference/is_user_logged_in) and [`wp_nav_menu()`](http://codex.wordpress.org/Function_Reference/wp_nav_menu)" and get rid of the "Reference:" and two links on the following lines.
- [ ] "theme_location" ← This should be code style, i.e., `theme_location`. 
- [ ] "check the documentation for `wp_nav_menu()`." ← Add to that line something that also suggests reviewing the codebase for the theme being used to figure out what the menu names are.
- [ ] "You can use the function is_user_logged_in() in the template files for the Registration and Directory pages." ← Remove this line altogether. It doesn't seem necessary.

**Comment by renzms** [comment]
@raamdev Updated, and ready for checking! Thanks again!

**Comment by raamdev** [comment]
@renzms Looks great! Thank you. 

#### Marking this article Approved as of 2015-10-07

**Comment by raamdev** [comment]
@renzms FYI, I made a few last-minute edits here: https://github.com/websharks/s2member-kb/commit/409d9bc517605df4db131cba0cafb8d89079b4a7
