### ISSUE TITLE
Integrating AWeber

### ISSUE THREAD

**Issue by kristineds** [websharks/s2member-kb#271]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Integrating AWeber](http://s2member.com/kb-article/integrating-aweber/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2015/271-integrating-aweber.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2015/271-integrating-aweber.md)

---

**Comment by raamdev** [comment]
@kristineds Looking great! I know this isn't done yet, but here's some initial feedback:

- [ ] "we recommend using Aweber, MailChimp, and GetResponse." ← I would say "or" instead of "and"
- [ ] "To get started, you will need your Aweber account, [Aweber API Authorization code)" ← Before this sentence I would add something that says, "In this article we're going to explain how to integrate Aweber with s2Member so that new members are automatically added to your Aweber list(s) and removed or transitioned to another list when they are upgraded, downgraded, or deleted."
- [ ] "Introduction" ← You don't need to add this header here. When the KB Article is published, the title of the KB Article will be right above the first paragraph making it clear that the first paragraph is the introduction.

**Comment by kristineds** [comment]
@raamdev Thanks for the feedback! I have updated the article and added relevant screenshots and links. If you could review it when you get a chance. :)

**Comment by raamdev** [comment]
@kristineds Looking great! Here's one more thing:

- [ ] "You will also need either an Aweber API Authorization code (if you choose the API method) or the Custom Email Parser for the s2Member application." ← You mention the Custom Email Parser but this article doesn't describe how to use it at all. You might want to change that sentence to make it a bit more clear that this article focuses on using the API method.

**Comment by raamdev** [comment]
@jaswsinc This looks almost ready to go. Would you mind doing a quick accuracy review for me when you get a chance?

**Comment by kristineds** [comment]
@raamdev @jaswsinc I deleted the part about Custom Email Parser to avoid confusion. :)

**Comment by jaswsinc** [comment]
Cool. Yeah, the Email Parser is only a part of the existing release for back compat. It is being deprecated and we can stop suggesting the Email Parser now. This article looks great!

Couple of minor things:

- Aweber should be **AWeber** (capital W).

- _moving a Member from a Aweber List that applies_
  Should be, "**an** Aweber List"

**Comment by kristineds** [comment]
@jaswsinc Good catch! I have fixed those minor revisions including the title. :)

**Comment by raamdev** [comment]
@kristineds Sweet! One last thing I noticed:

- [ ] For each of the screenshots, please create an appropriate alt-text (i.e., instead of `![screen shot 2015-10-27 at 1 55 06 am]` use something like `![s2Member AWeber List IDs]`. That text will appear for anyone who has images disabled in their browser, or for those accessing the web via an accessibility device or screen reader so it's good practice to make those somewhat descriptive of what's being shown in the image.

**Comment by kristineds** [comment]
@raamdev Ha! Forgot about that. Thanks for reminding me. Alt-text for those screenshots have been updated. :+1:

**Comment by raamdev** [comment]
@kristineds One other thing I noticed:

- [ ] I see you used `www.s2member.com` in several links in this article. Note that `www.s2member.com` is now `s2member.com` (without the `www`). Please replace any `www.s2member.com` links with `s2member.com`. (Both versions will work, as we have www.s2member.com redirecting to s2member.com, but we should be using the newer version whenever possible.)

**Comment by kristineds** [comment]
@raamdev Those links (`www.s2member.com` links with `s2member.com`) have been updated. :)

**Comment by raamdev** [comment]
@kristineds Nice work! I'm marking this **approved as of 2015-10-29**.

**Comment by raamdev** [comment]
@kristineds FYI, here are a few final edits I made: https://github.com/websharks/s2member-kb/commit/df1878322fd70383b5983d84755626cddbe1077c
