### ISSUE TITLE
Testing s2Member Access Control with User Switching

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#285]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Testing s2Member Access Control with User Switching](http://s2member.com/kb-article/testing-s2member-access-control-with-user-switching/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/285-testing-s2member-access-control-with-user-switching.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/285-testing-s2member-access-control-with-user-switching.md)

---

**Comment by jaswsinc** [comment]
@renzms  Great work on this! I see you closed the other issue in favor of this one. Awesome!

I'm skimming over it real quick to see if I can spot any areas of improvement. I'll leave some quick comments here as I do.

> The current work around

Check for consistency with this word. "work around" should be one word in all places; i.e., workaround. I'm guilting of spelling this wrong myself, so I just looked it up. haha


> Logging in or Logging out to switch between users

"Logging out" does not need a capital L within the sentence.

> Using the User Switching Plugin

You quoted something from their plugin I believe. I suggest making it clear that you are quoting what their plugin says before you introduce the quote, and then also provide a link to the source of that quote.

For instance, right before quote you might have:

The developers of this plugin write...
Source: `<URL here>`

> Go to User > Add New User,

Please use the `→` symbol for all software and/or Dashboard paths. Just for consistency in our articles.

> For more information please see:
> [s2If /] Simple Shortcode Conditionals
> How do WordPress Roles/Capabilities work?
> Video: Custom Capabilities for WordPress

I suggest making that a set of list items in Markdown.

```markdown
For more information please see:
- [s2If /] Simple Shortcode Conditionals
- How do WordPress Roles/Capabilities work?
- Video: Custom Capabilities for WordPress
```

Note also that any instance of a WP shortcode must always be encapsulated by backticks to explicitly declare that it is code that should not be rendered once this is published at s2member.com.

 ```markdown
For more information please see:
- `[s2If /]` Simple Shortcode Conditionals
- How do WordPress Roles/Capabilities work?
- Video: Custom Capabilities for WordPress
```

**Comment by renzms** [comment]
@jaswsinc 

Thanks for review!

>Check for consistency with this word. "work around" should be one word in all places; i.e., workaround. I'm guilting of spelling this wrong myself, so I just looked it up. haha

What's funny is I spelled it correctly the first time around. Lol

>Note also that any instance of a WP shortcode must always be encapsulated by backticks to explicitly declare that it is code that should not be rendered once this is published at s2member

Right, I almost forgot s2Member is actually running s2Member on the site!

```
Changelog:
- corrected spelling of **workaround**
- de-capitalisation of logging
- User Switching explanation quoted and cited
- Adjusted to use the `→` symbol for all software and/or Dashboard paths.
- Made set list of items for other KBA links
- added " ` " to make sure `s2If` shortcode is not rendered on site when published
```

**Comment by renzms** [comment]
@raamdev Ready for review, thanks.

**Comment by raamdev** [comment]
@renzms Nice! This looks like an article that will get referenced frequently. :-) 

I did an initial review of your draft. Here's some feedback. Please try to review your drafts carefully for spelling/grammar mistakes and organizational flow and layout. Each section needs to be more well-rounded.

---

> Testing s2Member Level Access / CCaps Enabled using User Switching

Please change the title to "Testing s2Member Access Control with User Switching" (in the GitHub issue _and_ the YAML markup).

> The following methods allows

Should be "The following method allows".

> s2Member admins

Please use "site owners"; that's the term we use throughout our KB articles when referring to the owner of the website administering s2Member. If you say "s2Member admins", it might be misunderstood as "WebSharks/s2Member support reps". 

> as one of their customers

Please use "users" or "subscribers" when referring to the site owners users; saying "customers" can be confusing.



> `ccaps`.

Please use "Custom Capabilities" instead of `ccaps` when referring to Custom Capabilities. The only time you should use it in a code style is when referring to the shortcode attribute itself (`ccaps=""`) or when referring to a specific (or example) Custom Capability (e.g., `pro` or `pro,unlimited`). 



> you can easily test and switch between different users with different membership level or

Should be "levels".

> Using the User Switching Plugin

This section is a bit unorganized. It starts with a list of bullet points by the plugin developer without a sufficient introduction of the User Switching plugin itself. I would spent a few more sentences summarizing why the User Switching plugin is useful and how it can be used.

I would also preface the list of security-related things with something like, "Is the User Switching plugin safe? Do you need to know users passwords? Here's what the User Switching plugin developers have to say about security:"

The paragraphs that explain how to use the User Switching plugin are separated from the screenshots, which makes it feel like you're just repeating yourself with the screenshots. I suggest creating a H3 section in there with something like "How to Use the User Switching Plugin" that outlines the steps.

> Custom Code Method
> WARNING - MU plugin file for testing purposes only.

The double-headings look wrong. Maybe use bold text for the warning instead of a header.

The Custom Code Method section also has no introduction; it starts with a path to a file, which just doesn't make sense. Each section should start with a sentence or paragraph introducing what the section is about.


> NOTE We highly suggest using the plugin over the custom solution. It is likely to offer better security and it will be easier to use.

This should go somewhere near the very top, in the introduction. And it shouldn't be a "NOTE"; it should just be a sentence in its own paragraph.

**Comment by renzms** [comment]
---

- [x] > Testing s2Member Level Access / CCaps Enabled using User Switching

Please change the title to "Testing s2Member Access Control with User Switching" (in the GitHub issue _and_ the YAML markup).

- [x] > The following methods allows

Should be "The following method allows".

- [x] > s2Member admins

Please use "site owners"; that's the term we use throughout our KB articles when referring to the owner of the website administering s2Member. If you say "s2Member admins", it might be misunderstood as "WebSharks/s2Member support reps". 

- [x] > as one of their customers

Please use "users" or "subscribers" when referring to the site owners users; saying "customers" can be confusing.



- [x] > `ccaps`.

Please use "Custom Capabilities" instead of `ccaps` when referring to Custom Capabilities. The only time you should use it in a code style is when referring to the shortcode attribute itself (`ccaps=""`) or when referring to a specific (or example) Custom Capability (e.g., `pro` or `pro,unlimited`). 



- [x] > you can easily test and switch between different users with different membership level or

Should be "levels".

- [x] > Using the User Switching Plugin

This section is a bit unorganized. It starts with a list of bullet points by the plugin developer without a sufficient introduction of the User Switching plugin itself. I would spent a few more sentences summarizing why the User Switching plugin is useful and how it can be used.

- [x] I would also preface the list of security-related things with something like, "Is the User Switching plugin safe? Do you need to know users passwords? Here's what the User Switching plugin developers have to say about security:"

- [x] The paragraphs that explain how to use the User Switching plugin are separated from the screenshots, which makes it feel like you're just repeating yourself with the screenshots. I suggest creating a H3 section in there with something like "How to Use the User Switching Plugin" that outlines the steps.

- [x] > Custom Code Method
> WARNING - MU plugin file for testing purposes only.

The double-headings look wrong. Maybe use bold text for the warning instead of a header.

- [x] The Custom Code Method section also has no introduction; it starts with a path to a file, which just doesn't make sense. Each section should start with a sentence or paragraph introducing what the section is about.


- [x] > NOTE We highly suggest using the plugin over the custom solution. It is likely to offer better security and it will be easier to use.

- [x] This should go somewhere near the very top, in the introduction. And it shouldn't be a "NOTE"; it should just be a sentence in its own paragraph.

**Comment by raamdev** [comment]
@renzms Nice! Here's some more feedback:

---

> short code

- [ ] Should be 'shortcode'. 

> Current Workaround

- [ ] I would consolidate this section into a paragraph at the top, as part of the intro. We don't need a whole separate section for this. Also, no need to make a list--just summarize the steps in a single sentence. Users coming to this article will likely already be familiar with this tedious process, which is why they're looking for another way of doing it.

> Using the User Switching Plugin, you can easily test and switch between

- [ ] Link to the 'User Switching' plugin here as well. Also, it should be "User Switching plugin", not Plugin with a capital P.

> Features 
> Security

- [ ] In the Features and Security lists that you quote from the User Switching plugin developers, remove those headers ('Features' and 'Security'). Just the list items themselves should be quoted.

> Using the User Switching Plugin

- [ ] This should just be "About the User Switching Plugin", as your next header is called "How to Use the User Switching Plugin". 

> How to Use the User Switching Plugin

- [ ] Add a short introduction to this section, one or two sentences that summarize how to use the plugin. Also, convert the list items in this section to an ordered list (1., 2., etc.). These appear to be steps to follow, so bullets don't really make sense here. (Note: To make images part of a list item, add 5 spaces in front of the image markup.)

> Common concerns of users may be:

- [ ] Add an H3 header right above this called "Is it safe?"

> Common concerns of users may be:

- [ ] The person reading this article is "the user", so this sentence doesn't sound right. Address the reader ("concerns you may have"), not 'users'.

**Comment by raamdev** [comment]
@jaswsinc My feeling is that we shouldn't even be posting the MU Plugin example ("Custom Code Method" in this article) in a KB Article on our website. In this case, that seems like a bad idea from a general web security perspective (i.e., makes it too easy for a novice site owner to try using and end up with a potential security hole). I recommend that we move that code to a GitHub Gist and convert the entire "Custom Code Method" section into a little note at the bottom of this article that says something like "If you're a developer and you need more control over user switching, take a look at this method that uses an MU-Plugin.". Thoughts?

**Comment by renzms** [comment]
> I recommend that we move that code to a GitHub Gist and convert the entire "Custom Code Method" section into a little note at the bottom of this article that says something like "If you're a developer and you need more control over user switching, take a look at this method that uses an MU-Plugin.". Thoughts?

@raamdev @jaswsinc 

I agree with Raam, I think it would be better to remove that section altogether. I see how it can be useful for a developer as a starting point for some other custom solution they may have, but the point of the article was mainly to simplify the testing process via the User Switching plugin.

**Comment by jaswsinc** [comment]
@raamdev writes...

> I recommend that we move that code to a GitHub Gist and convert the entire "Custom Code Method" section into a little note at the bottom of this article that says something like "If you're a developer and you need more control over user switching, take a look at this method that uses an MU-Plugin.". Thoughts?

@renzms writes...

> I agree with Raam, I think it would be better to remove that section altogether. I see how it can be useful for a developer as a starting point for some other custom solution they may have, but the point of the article was mainly to simplify the testing process via the User Switching plugin.

---

Great points. That sounds like a plan to me; i.e., moving it to a Gist or excluding it entirely.

**Comment by renzms** [comment]
**Checklist**

---

> short code

- [ ] Should be 'shortcode'. 

> Current Workaround

- [ ] I would consolidate this section into a paragraph at the top, as part of the intro. We don't need a whole separate section for this. Also, no need to make a list--just summarize the steps in a single sentence. Users coming to this article will likely already be familiar with this tedious process, which is why they're looking for another way of doing it.

> Using the User Switching Plugin, you can easily test and switch between

- [ ] Link to the 'User Switching' plugin here as well. Also, it should be "User Switching plugin", not Plugin with a capital P.

> Features 
> Security

- [ ] In the Features and Security lists that you quote from the User Switching plugin developers, remove those headers ('Features' and 'Security'). Just the list items themselves should be quoted.

> Using the User Switching Plugin

- [ ] This should just be "About the User Switching Plugin", as your next header is called "How to Use the User Switching Plugin". 

> How to Use the User Switching Plugin

- [ ] Add a short introduction to this section, one or two sentences that summarize how to use the plugin. Also, convert the list items in this section to an ordered list (1., 2., etc.). These appear to be steps to follow, so bullets don't really make sense here. (Note: To make images part of a list item, add 5 spaces in front of the image markup.)

> Common concerns of users may be:

- [ ] Add an H3 header right above this called "Is it safe?"

> Common concerns of users may be:

- [ ] The person reading this article is "the user", so this sentence doesn't sound right. Address the reader ("concerns you may have"), not 'users'. 

> To switch back, you can switch back via the Dashboard Notification or the Admin Bar.

- [ ] The screenshot here has a big red bar through something. Please remove this. If you need to hide the name of something before taking a screenshot, just use the Chrome inspector to edit the markup and change it to something else (e.g., "Example Admin").

**Comment by raamdev** [comment]
> and create your **test Users**.

- [ ] Change this to "and create one or more test users with the appropriate s2Member Level and Custom Capabilities (optional)."

> Is it safe?

- [ ] Change this to "Is User Switching Safe?" and move that entire section underneath "How to Use the User Switching Plugin"; it makes more sense for it to come after.


> About the User Switching Plugin

- [ ] Change this to "The User Switching Plugin"

---

I removed the Custom Code Method section and updated that for you.

**Comment by renzms** [comment]
> I removed the Custom Code Method section and updated that for you.

@raamdev 

Okay, thanks and update for review!

**Comment by raamdev** [comment]
@renzms I'm marking this **Approved as of 2016-03-10**. Thank you! I'll do some final editing and publish this soon. :-)
