### ISSUE TITLE
I Just Updated s2Member and My Shortcodes are Showing!

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#287]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
[  ] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [I Just Updated s2Member and My Shortcodes are Showing!](http://s2member.com/kb-article/i-just-updated-s2member-and-my-shortcodes-are-showing/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2016/287-i-just-updated-s2member-and-my-shortcodes-are-showing.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2016/287-i-just-updated-s2member-and-my-shortcodes-are-showing.md)

---

**Comment by patdumond** [comment]
@raamdev, @jaswsinc For your review.

**Comment by raamdev** [comment]
@patdumond Looks great to me. We definitely needed an article for this one. :-) Thank you.

Here's some feedback:

- Explain somewhere that the version of s2Member Pro must always match the version of s2Member Framework, and if you update Framework without updating Pro, the Pro Add-On will not activate. 
- Explain somewhere that since s2Member Pro-Forms require s2Member Pro, when the Pro Add-On is not activated the Pro-Form shortcodes will not get processed and will instead show up as plain text. 
- State that the issue of Pro-Forms showing up as plain-text is almost always the result of the s2Member Pro Add-On not being properly activated.

(Perhaps mention these points somewhere near the top, in the introduction, so more experienced users don't need to filter through the rest of the article to learn that point.)

**Comment by raamdev** [comment]
@patdumond One other minor thing: I noticed the checklist formatting at the top is wrong. You have `[]` when it should be `- [ ]` or `- [x]`:

![2016-01-23_09-07-37](https://cloud.githubusercontent.com/assets/53005/12530581/d8765e3a-c1b0-11e5-8546-6a1bfaf93b7f.png)

**Comment by jaswsinc** [comment]
Related article: http://s2member.com/kb-article/why-are-my-shortcodes-showing-up-as-plain-text/

**Comment by patdumond** [comment]
@jaswsinc: I searched for a similar article... Have I mentioned I don't like your search engine? ;) I'll put a link to that one at the end of mine.

@raamdev: I'll get on those changes after I eat lunch. Then I am going to finish that monster KBA if it kills me.

**Comment by patdumond** [comment]
@raamdev: Revised and ready for review.

**Comment by jaswsinc** [comment]
I didn't say it before, but I like this article a lot :-) It's wonderful. The screenshots make it easier to read. So even if we do have a similar article already, I'd upvote this one.

**Comment by jaswsinc** [comment]
Title: "My Shortcodes are Showing"
ha... That makes me laugh. I want to say, _"sounds like a personal problem.". :smile:

**Comment by Mugane** [comment]
This is a VERY serious problem with the S2 code! It should NEVER allow an update that breaks sites! How could even begin to think that this is acceptable behavior? I honestly can't believe this is happening. What a disaster!
