### ISSUE TITLE
Verify PayPal IPN w/ 3rd-party application using Proxy Key?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#29]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1CzwqHN
**Published KB Article:** http://s2member.com/kb-article/verify-paypal-ipn-w-3rd-party-application-using-proxy-key/

---

**Comment by Ashik72** [comment]
Thanks Jason opening the issue here. :)

Actually that's what I was expecting too. I set notification URL with a proxy key. - http://prntscr.com/5sgg5m

Now on that gateway (pagseguro) the generated button has some obligatory input fields. I kept them and also added fields required by s2. I was expecting to get all this data via POST method. Now whether the verification is fine or fails, shouldn't I get the all the post variables as log? But this is what I'm getting - log 1 (gateway-core-ipn.log) - http://pastebin.com/CVrMsgAg , log 2 (s2-http-api-debug-api.log , the last transaction only) - http://pastebin.com/42GJ9XV5
 
Might it be the payment gateway that's not sending all the required data or should I do something to get them?

I know it's not an area I should get support. But still it will be of great help. :)

Thanks!
