### ISSUE TITLE
Configuring s2Member Payment Gateways

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#306]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Configuring s2Member Payment Gateways](http://s2member.com/kb-article/configuring-s2member-payment-gateways/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/306-configuring-s2member-payment-gateways.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/306-configuring-s2member-payment-gateways.md)

---

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: The latest installment in the *s2Member's User Guide*. I haven't uploaded screenshots yet, but their locations are marked. This is ready for review. Thanks in advance.

**Comment by raamdev** [comment]
@patdumond Nice work. :-) I'll do a second review after @jaswsinc gets a chance to also review this, but here's some initial feedback:

----

> Supported Payment Gateways

I suggest removing this first header at the top of the article—having the article title followed immediately by another header doesn't look right when the article is published to s2Member.com.



> Your PayPal Merchant ID: At PayPal, see: Profile → Secure Merchant ID
> 
> Your PayPal Email Address: At PayPal, see: Profile → Email Accounts
> 
> Your PayPal API Username: At PayPal, see: Profile → API Access (or → Request API Credentials)

Please make these sorts of things into lists by prefixing them with a dash:

```
- Your PayPal Merchant ID: At PayPal, see: Profile → Secure Merchant ID
- Your PayPal Email Address: At PayPal, see: Profile → Email Accounts
```

The **Tax Rate Calculations (Pro-Form)** and **Authorize.net Account Details** sections also have two areas that could be turned into lists. Lists help break up the flow of things so the article doesn't feel like a wall of text to the reader.

> `&s2member_pro*ClickBank*return_success=`

Please double-check any areas in this article that use code style—I noticed a few areas that have erroneous asterisks in them.

**Comment by raamdev** [comment]
Also, this appears to be missing the paragraph near the top about this article being part of a bigger series.

**Comment by patdumond** [comment]
@raamdev: Thanks. Yeah, I remembered the opening paragraph and removing the title while I was in the shower the other morning, but I don't have waterproof paper in there. ;) I'll get all of these done. I'm also going to restructure the *Logging Configuration* into one section up above the individual payment gateways -- like I've done with SSL. 

I worked really hard to remove those Markdown errors, and there are fewer than before, but I'll always need a second set of eyes for those. :)  

Hope to get these revisions done tomorrow. That'll give you most of next week to review the revision. :)

**Comment by patdumond** [comment]
@raamdev: I believe I made all the requested revisions. If I missed any errant * or _, please post a copy/paste of the words in front and back of the bad code so I can find it. ;)

On changing items to a list, I did so where the item was a single paragraph. If it was multiple paragraphs I changed the bolded text at the beginning to the next level header (whatever that was in each case) to make it clear that all the following paragraphs go with THAT option setting. If you'd prefer I change them all to sub-headers, let me know and I will do that.

I also added the screenshots, so this is ready for another (hopefully final) review. Thanks in advance.

**Comment by patdumond** [comment]
@raamdev: Found another screenshot with "top secret" information. Blurred it. 
@jaswsinc: Raam indicated that he was waiting for you to get a chance to review this. Please and thank you.

It's a big article and I know there will be things I missed the first, second, and third times around.

**Comment by jaswsinc** [comment]
#### Holy cow 🐮  This is super long and awesome. Nice work!!!

---

### Review of the article thus far...

> PayPal Website Payments Standard (w/Buttons) (s2Member Framework) (s2Member Pro)

There is a list of items where I found this line and in that list there are several instances of round brackets, followed by more round brackets, which makes this slightly difficult to read. I suggest dropping the brackets from `(w/Buttons)` and instead use brackets to indicate (s2Member) or (s2Member Pro) only in that part of the article.

---

> Support for the following payment gates is deprecated and no longer supported in current versions of s2Member Pro:

I'd like to remove this whole section as these have been deprecated for quite some time now and I don't feel the need to mention them again for the sake of showing what we don't support.

---

> If your chosen payment gateway does not require it today, they most likely will by the end of 2016.

I suggest removing this line because reading this two or three years from now is going to make the article feel more outdated than it should. The rest of the wording in that paragraph accurately describes the reasons, so I think just removing this one sentence is fine.

---

> To comply with payment gateway and PCI Compliance

Please link the words [PCI Compliance](https://s2member.com/kb-article/pci-compliance/) to this article.
https://s2member.com/kb-article/pci-compliance/

---

> Once you're live, you can add the Custom Field s2member_force_ssl = yes to any Post or Page to ensure it loads using https://.

Please link the words [Custom Field](https://codex.wordpress.org/Custom_Fields#Usage) to this URL:
https://codex.wordpress.org/Custom_Fields#Usage

---

> You can skip the SSL certificate during Development/Sandbox testing. SSL is not required until you officially go live. Once you're live, you can add the Custom Field s2member_force_ssl = yes to any Post or Page to ensure it loads using https://.

Actually, this entire paragraph is repeated in the next section below it, just in slightly different words. So I would remove one or the other for the sake of brevity.

---

> your visitors could see the infamous "Secure/Insecure" warnings in their browsers.

I suggest singular 'browser' on the end of this sentence, since most users will use just one browser.

---

> Forcing those specific Posts and Pages to be viewed over a secure SSL connection, assuming as your server supports the https protocol.

In this sentence it reads, _"assuming as your server"_, which seems wrong to me. I suggest removing the word 'as'.

---

> Or, you could force your entire site to be displayed via https: as detailed in the following s2Member Knowledge Base articles.

In various places in the article you have `https:` I suggest including the slashes there to help convey exactly what that means to a novice user who might not associate it with the address bar in their browser otherwise. So for instance, `https://` instead of just `https:`

---

> Introduction to TLS/SSL and Why You Need It on Your s2Member Site
> 
> Implementing SSL (HTTPS) on an s2Member Site
> 
> Forcing SSL

I suggest single line breaks between these list items in Markdown. Currently there are double line breaks which causes them to consume more real estate than they should and it makes it difficult to recognize them as being a part of a single list in this particular context.

---

> Note: PayPal Pro is not mandatory, s2Member is quite flexible. It is possible to integrate Pro-Forms without a PayPal Pro account, integrating Pro-Forms only with PayPal Express Checkout.

Please remove this section from the article and the associated screenshots. I hate to strip hard work from the article, but this functionality in s2Member was never something we really _wanted_ to support. It is referenced in another KB article or two already and I'd like to stop suggesting this in any other areas; so that fewer and fewer site owners take this path. Why? It leads to problems for us in support due to limitations associated with this technique. Pro-Forms for PayPal Pro are designed and intended for PayPal Pro. If you don't have a PayPal Pro account you really should stick with Buttons.

---

> We recommend (Consolidate wi/ Recurring Profile)

'wi/' should be just 'w/' in this sentence.

---

> No matter which option you choose, a first Payment (when applicable) will always be charged immediately. However, in cases where it is critical that a Member not gain access until their first payment has been fully captured, please choose Real-Time/Direct Pay. This tells s2Member to authorize and capture the first payment in real-time during checkout instead of consolidating it into the Recurring Profile.

The screenshot following this paragraph seems a bit out of place to me. Maybe you intended for it to be an illustration for the next section below it, I'm not sure. If that's the case, maybe an arrow pointing to the specific setting in this screenshot that you're discussing would help.

![](https://cloud.githubusercontent.com/assets/9320495/15786474/dd0f8b5a-298a-11e6-846f-2a962c773f7d.jpg)

---

> In other words, if you use the `&s2member_pro*ClickBank*return_success=http://...`

More of the asterisks that Raam mentioned. Please review the article for other areas where there is corruption of the Markdown syntax that results in misleading information in the final draft.

---

### Breaking this apart an option?

This article is really long. I don't mind the fact that it's long though. That's great for SEO when we have a few _really_ long keyword-rich articles.. What's bothering me is the number of topics all in a single KBA. I think the individual payment gateways should be broken apart and posted as separate articles, where each of those separate articles references the opening paragraphs in this article as an introduction to payment gateways in s2Member.

Another reason for this is that most site owners won't be integrating _all_ of the payment gateways, they'll be working with one in particular that they have chosen. So having a single article with everything just leads to a TL;DR scenario. But if we break it down we can still publish all of the information in a way that allows a reader to remain more focused on what they really need to know.

**Comment by patdumond** [comment]
@jaswsinc: Thanks for the thorough review. Yes, I can break it down into separate articles.

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: I've broken this into 5 articles: one for areas common to all payment gateways and one each for the gateways:

- [PayPal](https://github.com/websharks/s2member-kb/issues/311)
- [Stripe](https://github.com/websharks/s2member-kb/issues/312)
- [Authorize.net](https://github.com/websharks/s2member-kb/issues/313)
- [ClickBank](https://github.com/websharks/s2member-kb/issues/314)

All are ready for review.

**Comment by jaswsinc** [comment]
@patdumond @raamdev 
All of those individual articles look amazing to me, as does this one! 💯 

- @patdumond One final suggestion is that in _this_ article, which I'd also like to see published, you can link to those other individual articles please; i.e., at the top of this article where you've already listed the payment gateways, you can link to the individual articles that go over each of them in greater detail.

  _**Note:** For now you can just link them to the GitHub issues for each of those articles. The WPKBA plugin that handles the conversion for us is smart enough to automate the link updates for you automatically; i.e., it will interpret links to KB-related issues and point those automatically to the final draft that exists at s2Member.com once they are published._

**Comment by patdumond** [comment]
@jaswsinc: Thanks. I wanted to link to the other articles but didn't know the WPKBA plugin would do the conversion. Done.
@raamdev: Ready for (hopefully final) review. :)
