### ISSUE TITLE
Generating Forms and Links for Specific Post/Page Access

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#319]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Generating Forms and Links for Specific Post/Page Access](http://s2member.com/kb-article/generating-forms-and-links-for-specific-postpage-access/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/319-generating-forms-and-links-for-specific-postpage-access.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/319-generating-forms-and-links-for-specific-postpage-access.md)

---

**Comment by jaswsinc** [comment]
> Specific Post/Page Access is a very powerful feature of s2Member Pro that allows you to sell access to specific WordPress Posts and Pages. Specific Post/Page Access works independently of Membership Level Access.

Suggest linking the text, "independently of Membership Level Access" to the article that you reference in the beginning of the article. Just to be sure they catch the connection between this article and the other when they have questions about the difference. http://s2member.com/kb-article/understanding-specific-postpage-access-restrictions/

---

Everything else looks great to me. Maybe the one screenshot that looks like it has text selected could be improved a little (i.e., without selected text in the screenshot), but otherwise great! 

cc @raamdev for final review & publication.

**Comment by raamdev** [comment]
> AddOn

Should be "add-on".

> For a thorough explanation of how this feature works in *s2Member, please see Understanding Specific Post/Page Access Restrictions.

There's an erroneous asterisks there.

> This article is part of the s2Member User's Guide, a series of articles that cover the fundamentals of using s2Member.

I suggest adding a header after this sentence, something that helps visually separate the introduction from the first section.

> See WordPress Dashboard → s2Member (Pro) → PayPal Pro-Forms → Specific Post/Page (Buy Now) Forms

I suggest putting the first screenshot after this line, moving it higher in the article so that the reader has something to reference as they're reading the rest.

> - The first drop-down box contains a list of Posts and Pages that you have restricted using Specific Post/Page Access Restrictions. From this first box, you will select the page you want your Customers to be redirected to (and receive a link to via email) after a successful purchase.

I suggest reiterating here that if you don't see any Posts/Pages in the list, that means you haven't added any to the Specific Post/Page Restrictions.

@jaswsinc writes...
> Maybe the one screenshot that looks like it has text selected could be improved a little (i.e., without selected text in the screenshot)

Agreed.

----

Otherwise, looks great to me!

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: I made all the requested revisions to this KBA.
