### ISSUE TITLE
How can I show a Features Table on my Pro-Form?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#47]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1D9RofS
**Published KB Article:** http://s2member.com/kb-article/how-can-i-show-features-table-my-pro-form/

---

**Comment by jaswsinc** [comment]
> you'll see one of the fields is called "Description" when you generate the Pro-Form shortcode

Just wanted to note that the `desc=""` attribute is limited to `100` chars. Beyond this, s2Member Pro will throw up a warning in your Pro Form as a reminder that you should limit the number of characters used in this attribute. There is a limit because the description is passed through to the payment gateway, and the payment gateways often have limits as to how long it can be.

There's nothing to stop you from adding a description above the Pro Form shortcode itself though, in whatever way is desired; i.e. with HTML or any other sort of rich text.

**Comment by raamdev** [comment]
> Just wanted to note that the desc="" attribute is limited to 100 chars

Thanks! I updated the KB Article.

**Comment by jaswsinc** [comment]
Adding tag `pro-forms`.
