### ISSUE TITLE
How do I display the EOT on my Login Welcome Page?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#53]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1EUWFst
**Published KB Article:** http://s2member.com/kb-article/how-do-i-display-the-eot-on-my-login-welcome-page/

---

**Comment by raamdev** [comment]
Related to websharks/s2member#450

**Comment by yaronelh** [comment]
Here you are talking about displaying EOT. but sometimes you would like to display the EOT remaining on the trial period.

It took me a long time to find and create this code since I'm not a developer, 

<?php
$remaining = get_user_field('s2member_auto_eot_time');
$remaining = $remaining - time();

$days_remaining = floor($remaining / 86400);
$hours_remaining = floor(($remaining % 86400) / 3600);
//echo "There are $days_remaining days and $hours_remaining hours left";
echo "<strong>Trial ends in $days_remaining days</strong>, (remaining days are added to your subscription when upgrading)";

?>

**Comment by raamdev** [comment]
@yaronelh Thanks for the feedback! I'll update this KB Article soon.

**Comment by raamdev** [comment]
@jaswsinc In lieu of the new `[s2Eot /]` shortcode ([\[s2Eot /\] Shortcode Documentation](http://s2member.com/kb-article/s2eot-shortcode-documentation/)) I have updated this KB article to reflect using the new shortcode instead of providing a PHP example.

However, @yaronelh's example above provides an interesting scenario that the `[s2Eot /]` shortcode does not yet cover. Do you think it makes sense to add such functionality into the `[s2Eot /]` shortcode (calculating the remaining trial period), or would a whole new shortcode for that purpose be in order? It seems to me the latter, as the `[s2Eot /]` shortcode already feels rather heavy.

Thoughts?

**Comment by jaswsinc** [comment]
> or would a whole new shortcode for that purpose be in order? It seems to me the latter, as the [s2Eot /] shortcode already feels rather heavy.

 I agree. That's a great idea. A new shortcode sounds like a good idea also.

---

@yaronelh Here's another way to generate this:

```php
<?php
$eot = s2member_eot();
if ($eot['time'] && $eot['tense'] === 'future') {
  echo 'Trial expires in '.esc_html(human_time_diff(time(), $eot['time'])); // e.g., Trial expires in 5 days.
}
```

See also: [`s2member_eot()` documentation](https://github.com/websharks/s2member/blob/150722/s2member/includes/functions/api-functions.inc.php#L2758)

---

Here's an example that checks for a `fixed` EOT time instead of a possible next payment time. Also, this runs an additional check that looks to see if the user has ever paid you.

```php
<?php
$eot = s2member_eot();
if ($eot['time'] && $eot['tense'] === 'future' && $eot['type'] === 'fixed' && !get_user_option('s2member_last_payment_time')) {
  echo 'Trial expires in '.esc_html(human_time_diff(time(), $eot['time'])); // e.g., Trial expires in 5 days.
}
```

See also: [`s2member_eot()` documentation](https://github.com/websharks/s2member/blob/150722/s2member/includes/functions/api-functions.inc.php#L2758)

**Comment by raamdev** [comment]
> A new shortcode sounds like a good idea also.

@jaswsinc I was about to create a new GitHub issue for a new `[s2Eot-Trial /]` shortcode, but I realized that separating that functionality from the existing `[s2Eot /]` shortcode is going to make things challenging: What if I want to show:

- Days until Trial Ends

OR

- Fixed-Term Subscription End Date

OR 

- Next Payment Date

How would we achieve that without PHP if we had two shortcodes? It seems to me now like the Trial EOT _should_ be part of the existing `[s2Eot /]` shortcode. Thoughts?

**Comment by jaswsinc** [comment]
That's a good point. The calculation itself is almost the same as the EOT calculation really.

However, I'd like this to be smart enough to know which billing cycle the customer is in. Otherwise, just saying "Trial ends in X days" could actually mean, "Next payment required in X days"; i.e., the trial itself could already be over.

Or, in some cases the trial is actually not a free period, it's just the initial period that might have been for a different amount. Thus, checking the last payment time is not going to be enough.

I guess what I'm saying is that we need a new API Function to expose `total_billing_cycles` and `billing_cycles_remaining`, and then we need to find a way to work that into a shortcode.

**Comment by raamdev** [comment]
@jaswsinc @yaronelh I've forked discussion on the topic of showing the Trial Remaining Time to this GitHub feature request: https://github.com/websharks/s2member/issues/670

I'm going to close this GitHub issue now in favor of continuing discussion on websharks/s2member#670.

**Comment by yaronelh** [comment]
Thanks for making a short code like [s2Eot /] Haven't tried it yet but it's on my list.
I'll follow this thread to see if my implementation is still valid (Works in all scenarios), or If a better way becomes available.

Also there is a small bug I wanted to report, Is it okay if I open an issue and you close it if it's not really a bug.

**Comment by raamdev** [comment]
> Is it okay if I open an issue and you close it if it's not really a bug.

Yes, definitely. :-) Please open a new issue with details here: http://github.com/websharks/s2member/issues/new
