### ISSUE TITLE
How can I debug my payment gateway integration?

### ISSUE THREAD

**Issue by brucewsinc** [websharks/s2member-kb#70]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

##### Additional TODO Items:

- [x] Update links in this article that point to the old site.

---

**Markdown File:** http://wsharks.com/1EpXNBx
**Published KB Article:** http://s2member.com/kb-article/how-can-i-debug-my-payment-gateway-integration/

---

**Comment by jaswsinc** [comment]
I think it should be noted that you're debugging WordPress overall, not just the s2Member plugin. We want to be clear that s2Member is not full of bugs, on the contrary it is often the case that s2Member is hindered by another plugin/theme that creates a conflict in some way.

So the steps above are really helpful, but I think this article should explain that a "fatal error" is something that can occur whenever one or more plugins are conflicting, or when there is an unexpected scenario encountered within WordPress. Turning on `WP_DEBUG` will reveal errors that are the underlying cause of the "white screen". That may or may not be related to s2Member.

**Comment by jaswsinc** [comment]
Even in cases where the "white screen" goes away when s2Member is disabled. That still does not point to s2Member as the true issue. I've seen many cases where disabling s2Member simply disabled a hook where another plugin was latching onto this hook and _it_ was causing the issue.

**Comment by raamdev** [comment]
Related to #71.

**Comment by brucewsinc** [comment]
> Even in cases where the "white screen" goes away when s2Member is disabled. That still does not point to s2Member as the true issue

I updated this with a bit more clear explanation on what we're debugging here.

**Comment by jaswsinc** [comment]
> the first step is usually to turn

Just wanted to point out the wording in this line. The use of "usually" caught my attention. Try to remember that, as a support rep., you're the end-all.

The fact that you're writing an answer to the question, "what should I do", builds an assumption that you're going to answer the question with an official response on "what you should do".

Therefore, the word "usually" should be used carefully, or not at all. Try to remember that this is not a forum entry, it's an official answer to a question that's going to appear in a KB for the plugin. The word "usually" could be removed with, "the first step is...", as a matter of fact.

As it exists right now, the very first paragraph in this article raises doubt in my mind about whether the article is official or not, and whether it's _actually_ going to help me. It's not a step-by-step that answers the question, because it starts with a paragraph that is more like somebody giving me yet another suggestion; e.g., like something I'd find in a forum somewhere.

> If you are having issues with s2Member's Buttons or Pro Forms, the first step is usually to turn on s2Member's Logging in this portion of your Dashboard:

**Comment by jaswsinc** [comment]
- Adding `troubleshooting` tag.
- General cleanup. A few changes in wording.
- Updating the title of this article.
